//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenIsland.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Player_Color1 {
            get {
                return ((global::System.Drawing.Color)(this["Player_Color1"]));
            }
            set {
                this["Player_Color1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Player_Color2 {
            get {
                return ((global::System.Drawing.Color)(this["Player_Color2"]));
            }
            set {
                this["Player_Color2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color Player_Color3 {
            get {
                return ((global::System.Drawing.Color)(this["Player_Color3"]));
            }
            set {
                this["Player_Color3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color Player_Color4 {
            get {
                return ((global::System.Drawing.Color)(this["Player_Color4"]));
            }
            set {
                this["Player_Color4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color Player_Color5 {
            get {
                return ((global::System.Drawing.Color)(this["Player_Color5"]));
            }
            set {
                this["Player_Color5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color Player_Color6 {
            get {
                return ((global::System.Drawing.Color)(this["Player_Color6"]));
            }
            set {
                this["Player_Color6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pink")]
        public global::System.Drawing.Color Player_Color7 {
            get {
                return ((global::System.Drawing.Color)(this["Player_Color7"]));
            }
            set {
                this["Player_Color7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Olive")]
        public global::System.Drawing.Color Player_Color8 {
            get {
                return ((global::System.Drawing.Color)(this["Player_Color8"]));
            }
            set {
                this["Player_Color8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color Player_Color9 {
            get {
                return ((global::System.Drawing.Color)(this["Player_Color9"]));
            }
            set {
                this["Player_Color9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Player_Controller1 {
            get {
                return ((int)(this["Player_Controller1"]));
            }
            set {
                this["Player_Controller1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Player_Controller2 {
            get {
                return ((int)(this["Player_Controller2"]));
            }
            set {
                this["Player_Controller2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Player_Controller3 {
            get {
                return ((int)(this["Player_Controller3"]));
            }
            set {
                this["Player_Controller3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Player_Controller4 {
            get {
                return ((int)(this["Player_Controller4"]));
            }
            set {
                this["Player_Controller4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Player_Controller5 {
            get {
                return ((int)(this["Player_Controller5"]));
            }
            set {
                this["Player_Controller5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Player_Controller6 {
            get {
                return ((int)(this["Player_Controller6"]));
            }
            set {
                this["Player_Controller6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Player_Controller7 {
            get {
                return ((int)(this["Player_Controller7"]));
            }
            set {
                this["Player_Controller7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Player_Controller8 {
            get {
                return ((int)(this["Player_Controller8"]));
            }
            set {
                this["Player_Controller8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Player_Controller9 {
            get {
                return ((int)(this["Player_Controller9"]));
            }
            set {
                this["Player_Controller9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Dots_PlayerCount {
            get {
                return ((int)(this["Dots_PlayerCount"]));
            }
            set {
                this["Dots_PlayerCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Dots_BoardWidth {
            get {
                return ((int)(this["Dots_BoardWidth"]));
            }
            set {
                this["Dots_BoardWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Dots_BoardHeight {
            get {
                return ((int)(this["Dots_BoardHeight"]));
            }
            set {
                this["Dots_BoardHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"squares\"")]
        public string Dots_BoardType {
            get {
                return ((string)(this["Dots_BoardType"]));
            }
            set {
                this["Dots_BoardType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Ttt_PlayerCount {
            get {
                return ((int)(this["Ttt_PlayerCount"]));
            }
            set {
                this["Ttt_PlayerCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Ttt_BoardWidth {
            get {
                return ((int)(this["Ttt_BoardWidth"]));
            }
            set {
                this["Ttt_BoardWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Ttt_BoardHeight {
            get {
                return ((int)(this["Ttt_BoardHeight"]));
            }
            set {
                this["Ttt_BoardHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Ttt_WinLength {
            get {
                return ((int)(this["Ttt_WinLength"]));
            }
            set {
                this["Ttt_WinLength"] = value;
            }
        }
    }
}
